### ISSUE TITLE
Zend\Mail doesn't work with Smtp transport via SSL connection ..

### ISSUE THREAD

**Issue by BnitoBzh** [JouwWeb/SlmQueue#130] opened 2014-10-08 10:08 UTC
I use this module to send my emails in the background via Zend / Mail, but my SMTP server allows only SSL connections. 
After a few minutes of inactivity to send email, the tail always returns the same error with a message "SSL broken pipe". 
Impossible to miss even creating a Mailer Service on the fly, which returns me an error like this: "SSL operation failed with code 1 OpenSSL Error messages: error: 1409F07F: SSL routines: SSL3_WRITE_PENDING: bad write retry in ..."
I think this is due to the permanent php process, so that the mail function with Zend/Mail can not work with SlmQueue...

**Comment by mstrychalski** [comment] 2017-08-22 08:15
The problem is still not resolved and I have not been able to solve it yet. But we've tried to use swiftmailer instead of zend mail, and everything is working like a charm now. I suggest to switch to it if you have similar problem, and can switch library.

**Comment by roelvanduijnhoven** [comment] 2018-01-03 10:30
Thanks for the update @mstrychalski. I'll close this for now though; because this repo does nothing with SSL or mail and I think the problem lies outside this repo

**Closed by roelvanduijnhoven** 2018-01-03 10:30 UTC
Labels: invalid

**Comment by MatthiasKuehneEllerhold** [comment] 2018-01-03 10:41
@mstrychalski This could be a problem with the maximum connection lifetime. The SMTP Server will close the connection if nothing is sent over it after a while. Even if you constantly send a ping or NOOP, there is a maximum connection lifetime setting for most servers. Meaning they'll close the connection regardless.

What you have to do with zend-mail is recreate the connection every so often, see my PR here: https://github.com/zendframework/zend-mail/pull/172

We're using zend-mail together with SlmQueue and it works. You just have to guess (?) the connection timelimit of your SMTP server. It wasnt properly document in ours...

**Comment by roelvanduijnhoven** [comment] 2018-01-03 10:53
Mm. What about introducing a section in this repo that gives some general hints about problems with long-connectivity @MatthiasKuehneEllerhold? We know this is also a problem with database connections :thinking:. 

If you like the idea; would you be willing to add a PR regarding the SSL connection to a section in the docs?

**Comment by MatthiasKuehneEllerhold** [comment] 2018-01-03 10:59
This problem is not specific to SSL connections because the same happens with HTTP connections. 

The error message is different on a plain HTTP connection:
```
Notice: fwrite(): send of 6 bytes failed with errno=32 Broken pipe in ./zend-mail/src/Protocol/AbstractProtocol.php on line 255
Fatal error: Uncaught Zend\Mail\Protocol\Exception\RuntimeException: Could not read from 127.0.0.1 in ./zend-mail/src/Protocol/AbstractProtocol.php:301
```

But I'm not sure if its the same error that @mstrychalski describes. He switched libraries and the error was gone. I dont know if his new library has the auto-reconnect feature that zend-mail misses (until my PR is merged).

Adding some text to the documentation will help for sure. I'll try to whip up something and will need your input (english isnt my main language ;)).

**Comment by roelvanduijnhoven** [comment] 2018-01-03 11:06
No problem @MatthiasKuehneEllerhold, mention me when you have something and I'll gladly give feedback :).

**Comment by roelvanduijnhoven** [comment] 2018-01-04 07:43
Issue #177 is similar. Let's use that to keep track of this effort.
